SELECT USER
FROM DUAL;

--○ 기존 테이블 제거
DROP TABLE TBL_MEMBERLIST;


--○ 실습 테이블 다시 생성
CREATE TABLE TBL_MEMBERLIST
( ID        VARCHAR(30)
, PW        VARCHAR(20)
, NAME      VARCHAR(50)
, TEL       VARCHAR(50)
, EMAIL        VARCHAR(100)
, CONSTRAINT MEMBERLIST_ID_PK PRIMARY KEY(ID)
);

INSERT INTO TBL_MEMBERLIST(ID, PW, NAME, TEL, EMAIL) VALUES('admin', CRYPTPACK.ENCRYPT('java006$', 'java006'), '이연주', '010-1111-1111', 'yjooo0816@gmail.com');

SELECT *
FROM TBL_MEMBERLIST;

COMMIT;