SELECT USER
FROM DUAL;

DROP TABLE TBL_MEMBERLIST;

CREATE TABLE TBL_MEMBERLIST
( MID   NUMBER
, NAME  VARCHAR(20)
, TELEPHONE     VARCHAR(40)
, CONSTRAINT MEMBERLIST_MID_PK PRIMARY KEY(MID)

);

DROP SEQUENCE MEMBERLISTSEQ;

CREATE SEQUENCE MEMBERLISTSEQ
NOCACHE;


INSERT INTO TBL_MEMBERLIST(MID, NAME, TELEPHONE)
VALUES(MEMBERLISTSEQ.NEXTVAL, '김태형', '010-1111-1111');


SELECT MID, NAME, TELEPHONE
FROM TBL_MEMBERLIST
ORDER BY MID;

COMMIT;

SELECT COUNT(*) AS COUNT
FROM TBL_MEMBERLIST;

INSERT INTO TBL_MEMBERLIST(MID, NAME, TELEPHONE)
VALUES(MEMBERLISTSEQ.NEXTVAL, '우수정', '010-2222-2222');

COMMIT;


DELETE 
FROM TBL_MEMBERLIST
WHERE MID = '2';
