select user
from dual;




-- 테이블 생성
CREATE TABLE TBL_STUDENT
( SID NUMBER
, NAME VARCHAR2(30)
, TEL VARCHAR2(40)
, CONSTRAINT STUDENT_SID_PK PRIMARY KEY(SID)
);


-- 샘플 데이터 입력
INSERT INTO TBL_STUDENT(SID, NAME, TEL)
VALUES(1, '이호석', '010-1111-1111');

INSERT INTO TBL_STUDENT(SID, NAME, TEL)
VALUES(2, '최선하', '010-2222-2222');

INSERT INTO TBL_STUDENT(SID, NAME, TEL)
VALUES(3, '임소민', '010-3333-3333');

INSERT INTO TBL_STUDENT(SID, NAME, TEL)
VALUES(4, '홍은혜', '010-4444-4444');



-- 테이블 생성
CREATE TABLE TBL_GRADE
(SID NUMBER
,SUB1 NUMBER(3)
,SUB2 NUMBER(3)
,SUB3 NUMBER(3)
,CONSTRAINT GRADE_SID_PK PRIMARY KEY(SID)
,CONSTRAINT GRADE_SID_FK FOREIGN KEY(SID)
            REFERENCES TBL_STUDENT(SID)
,CONSTRAINT GRADE_SUB1_CK CHECK(SUB1 BETWEEN 0 AND 100)
,CONSTRAINT GRADE_SUB2_CK CHECK(SUB2 BETWEEN 0 AND 100)
,CONSTRAINT GRADE_SUB3_CK CHECK(SUB3 BETWEEN 0 AND 100)
);

-- 샘플 데이터 입력
INSERT INTO TBL_GRADE(SID, SUB1, SUB2, SUB3)
VALUES(1, 90, 80, 70);

INSERT INTO TBL_GRADE(SID, SUB1, SUB2, SUB3)
VALUES(2, 92, 82, 72);

INSERT INTO TBL_GRADE(SID, SUB1, SUB2, SUB3)
VALUES(3, 70, 60, 50);

INSERT INTO TBL_GRADE(SID, SUB1, SUB2, SUB3)
VALUES(4, 74, 64, 54);


SELECT *
FROM TBL_STUDENT;

SELECT *
FROM TBL_GRADE;


COMMIT;



-- 뷰... 생성(학생)
CREATE OR REPLACE VIEW STUDENTVIEW 
AS
SELECT SID, NAME, TEL
,(SELECT COUNT(*) FROM TBL_GRADE WHERE SID = S.SID) AS SUB
FROM TBL_STUDENT S;

-- 뷰 생성(점수)
CREATE OR REPLACE VIEW GRADEVIEW
AS
SELECT S.SID AS SID
, S.NAME AS NAME
, G.SUB1 AS SUB1
, G.SUB2 AS SUB2
, G.SUB3 AS SUB3
, (G.SUB1 + G.SUB2 + G.SUB3) AS TOT
, (G.SUB1 + G.SUB2 + G.SUB3)/3 AS AVG
, (CASE WHEN (G.SUB1 + G.SUB2 + G.SUB3)/3 < 60 THEN '불합격'
 WHEN (G.SUB1 <= 40) OR (G.SUB2 <= 40) OR (G.SUB3<= 40) THEN '과락'
ELSE '합격'
END) AS CH
FROM TBL_STUDENT S JOIN TBL_GRADE G
ON S.SID = G.SID;


SELECT SID, NAME,TEL, SUB
FROM STUDENTVIEW;

SELECT SID, NAME, SUB1, SUB2, SUB3, TOT, AVG, CH
FROM GRADEVIEW;


-- ○ 인원 수 확인
SELECT COUNT(*) AS COUNT
FROM TBL_STUDENT;

