/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.54
 * Generated at: 2022-06-10 05:40:05 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class user_005fdelievery_005fmodify_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("jar:file:/C:/SpringMVCStudy/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/comfit/WEB-INF/lib/standard.jar!/META-INF/fmt.tld", Long.valueOf(1098678690000L));
    _jspx_dependants.put("/WEB-INF/lib/standard.jar", Long.valueOf(1654790812624L));
    _jspx_dependants.put("jar:file:/C:/SpringMVCStudy/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/comfit/WEB-INF/lib/standard.jar!/META-INF/c.tld", Long.valueOf(1098678690000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

   request.setCharacterEncoding("UTF-8");
   String cp = request.getContextPath();

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<title>배송 판매글 수정(입찰 없을 시)</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(cp );
      out.write("/css/bootstrap.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(cp );
      out.write("/css/inputstyle.css\">\r\n");
      out.write("<script type=\"text/javascript\" src=\"http://code.jquery.com/jquery.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"/js/bootstrap.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\t$(document).ready(function()\r\n");
      out.write("\t{\r\n");
      out.write("\t\t// 테스트\r\n");
      out.write("\t\t//alert(\"창열림\");\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(\"[name=asRadio]\").change(function()\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\t$(\"#asDate\").attr(\"disabled\", false);\r\n");
      out.write("\t\t\t//alert($(this).val());\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tif ($(this).val() == \"불가능\")\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\t $(\"#asDate\").attr(\"disabled\", true);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<div class=\"header\">\r\n");
      out.write("\t");
      if (_jspx_meth_c_005fimport_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"container\" style=\"padding-top: 80px;\">\r\n");
      out.write("\t<p class=\"fs-3\" style=\"font-weight: bold;\">\r\n");
      out.write("\t\t판매글 수정-배송(입찰 없을 시)\t\r\n");
      out.write("\t</p>\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- 입력 페이지를 복사해서 만든 수정 페이지 -->\r\n");
      out.write("\t<!-- 기존에 입력해둔 값을 넣어주는 속성만 추가하면 됨 -->\r\n");
      out.write("\t<div class=\"input_box\" style=\"padding-left: 5%; padding-top: 10%;\">\r\n");
      out.write("\t\t<table style=\"width: 100%;\">\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<th>제목<span class=\"star\">*</span></th>\r\n");
      out.write("\t\t\t\t<td colspan=\"3\"><input class=\"form-control\" id=\"exampleFormControlInput1\" type=\"text\" placeholder=\"제목을 입력해주세요.\" style=\"width: 86%;\"/>\r\n");
      out.write("\t\t\t\t<p align=\"right\" style=\"font-size: 3px; margin-right: 16%;\">32/32</p>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<th>물품 카테고리<span class=\"star\">*</span>\r\n");
      out.write("\t\t\t\t <p style=\"font-weight: normal; font-size: 7pt;\">상품과 일치하는 카테고리를 선택해주세요.\r\n");
      out.write("                 <br>적합하지 않을 경우 운영자에 의해 조정될 수 있습니다.</p>\r\n");
      out.write("                </th>\r\n");
      out.write("\t\t\t\t<td width=\"20%;\">카테고리\r\n");
      out.write("\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t<select class=\"form-select\" name=\"category\" style=\"width: 90%; height: 35px;\">\r\n");
      out.write("\t\t\t\t\t<option selected=\"selected\">카테고리</option>\r\n");
      out.write("\t\t\t\t\t<option>모니터</option>\r\n");
      out.write("\t\t\t\t\t<option>마우스</option>\r\n");
      out.write("\t\t\t\t\t<option>키보드</option>\r\n");
      out.write("\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t<td>물품명\r\n");
      out.write("\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" class=\"form-control\" id=\"productName\" placeholder=\"물품명을 입력해 주세요.\" style=\"width: 90%;\">\r\n");
      out.write("\t\t\t\t</td>\t\r\n");
      out.write("\t\t\t\t<td>제조사\r\n");
      out.write("\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" class=\"form-control\" id=\"productMaker\" placeholder=\"제조사를 입력해 주세요.\" style=\"width: 90%;\"/>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<!-- 공간맞추기용 th -->\r\n");
      out.write("\t\t\t\t<th>\r\n");
      out.write("\t\t\t\t</th>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<td colspan=\"2\">\r\n");
      out.write("\t\t\t\t\t물품검색\r\n");
      out.write("\t\t\t\t\t<div class=\"input-group mb-5\">\r\n");
      out.write("\t\t\t\t\t  <span class=\"input-group-text\" id=\"basic-addon1\"><i class=\"bi bi-search\"></i></span>\r\n");
      out.write("\t\t\t\t\t  <input type=\"text\" class=\"form-control\" placeholder=\"물품검색\" style=\"height:40px; width:100px;\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<th>희망 시작 가격<span class=\"star\">*</span>\r\n");
      out.write("\t\t\t\t <p style=\"font-weight: normal; font-size: 7pt;\">희망하는 가격을 적어주세요.</p>\r\n");
      out.write("                </th>\r\n");
      out.write("                <td colspan=\"3\"><input class=\"form-control\" id=\"price1\" type=\"text\" placeholder=\"희망 가격을 입력해주세요.\" style=\"width: 86%;\"/>\r\n");
      out.write("                <p style=\"color:blue; font-size: 10px;\">추천 가격보다 2배 이상은 입력할 수 없습니다.</p>\r\n");
      out.write("                </td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<th>즉시 구매 가격<span class=\"star\">*</span>\r\n");
      out.write("\t\t\t\t <p style=\"font-weight: normal; font-size: 7pt;\">즉시 거래 가격을 적어주세요.</p>\r\n");
      out.write("                </th>\r\n");
      out.write("                <td colspan=\"3\"><input class=\"form-control\" id=\"price2\" type=\"text\" placeholder=\"즉시구매 가격을 입력해주세요.\" style=\"width: 86%;\"/>\r\n");
      out.write("                <p style=\"color:blue; font-size: 10px;\">추천 가격보다 2배 이상은 입력할 수 없습니다.</p>\r\n");
      out.write("                </td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<th>물품 사진<span class=\"star\">*</span>\r\n");
      out.write("\t\t\t\t <p style=\"font-weight: normal; font-size: 7pt;\">최소 두장 이상 등록해 주세요.</p>\r\n");
      out.write("                </th>\r\n");
      out.write("                <td colspan=\"3\">\r\n");
      out.write("                \t<div style=\"width: 86%; height: 100%; border: 1px solid;\">\r\n");
      out.write("                \t\t<p style=\"text-align: center; font-size: 9px;\">\r\n");
      out.write("                \t\t<br>\r\n");
      out.write("                \t\t이미지 업로드(0/5)\r\n");
      out.write("                \t\t<br><br>\r\n");
      out.write("                \t\t최소 2개, 최대 5개까지 업로드 가능<br>\r\n");
      out.write("                \t\t파일 형식 : jpg / png 사이즈 : 가로 ??px, 세로 ??px 이상<br>\r\n");
      out.write("                \t\t※ 이미지를 등록하면 반영됩니다.\r\n");
      out.write("                \t\t</p>\r\n");
      out.write("                \t</div>\r\n");
      out.write("                \t<div class=\"d-grid gap-2 d-md-flex justify-content-md-end\" style=\"margin-right: 14%;\">\r\n");
      out.write("                \t<button type=\"button\" class=\"btn btn-primary btn-sm\">이미지 업로드</button>\r\n");
      out.write("                \t<button type=\"button\" class=\"btn btn-secondary btn-sm\">이미지 삭제</button>\r\n");
      out.write("                \t</div>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<th>A/S 가능 여부\r\n");
      out.write("                </th>\r\n");
      out.write("                <td colspan=\"3\">\r\n");
      out.write("                <div class=\"form-check form-check-inline\">\r\n");
      out.write("\t\t\t\t  <input class=\"form-check-input\" type=\"radio\" name=\"asRadio\" id=\"inlineRadio1\" value=\"유상\" checked=\"checked\">\r\n");
      out.write("\t\t\t\t  <label class=\"form-check-label\" for=\"inlineRadio1\">유상</label>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"form-check form-check-inline\">\r\n");
      out.write("\t\t\t\t  <input class=\"form-check-input\" type=\"radio\" name=\"asRadio\" id=\"inlineRadio2\" value=\"무상\">\r\n");
      out.write("\t\t\t\t  <label class=\"form-check-label\" for=\"inlineRadio2\">무상</label>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"form-check form-check-inline\">\r\n");
      out.write("\t\t\t\t  <input class=\"form-check-input\" type=\"radio\" name=\"asRadio\" id=\"inlineRadio3\" value=\"불가능\">\r\n");
      out.write("\t\t\t\t  <label class=\"form-check-label\" for=\"inlineRadio3\">불가능</label>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<input class=\"form-control\" id=\"asDate\" type=\"text\" placeholder=\"유효날짜 (연/월/일)\" style=\"width: 86%;\"/>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<th>\r\n");
      out.write("\t\t\t\t\t<div style=\"background-color: #C9E0F5; height: 70px; padding: 10px; width: 85%;\">\r\n");
      out.write("\t\t\t\t\t\t<p style=\"font-size: 9pt;\"> ※ 게시글 유지 기간</p>\r\n");
      out.write("\t\t\t\t\t\t<p style=\"font-size: 7pt; font-weight: normal;\">게시글 등록 시간부터 00일까지 유지됩니다.</p>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</th>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<td colspan=\"3\" rowspan=\"2\">\r\n");
      out.write("\t\t\t\t<textarea placeholder=\"코멘트 특이사항\" style=\"width:86%; height: 150px;\"></textarea>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<th style=\"margin-right: 10%;\">\r\n");
      out.write("\t\t\t\t\t<div style=\"background-color: #C9E0F5; height: 100px; padding: 10px; width: 85%;\">\r\n");
      out.write("\t\t\t\t\t\t<p style=\"font-size: 9pt;\"> ※ 코멘트 작성 시 주의사항</p>\r\n");
      out.write("\t\t\t\t\t\t<p style=\"font-size: 7pt; font-weight: normal;\">불필요한 개인 정보 노출 및 판매와 관련없는 문구\r\n");
      out.write("\t\t\t\t\t\t<br>등록 시 약관에 위배되어 제재될 수 있습니다.</p>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</th>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td colspan=\"4\">\r\n");
      out.write("\t\t\t\t\t<div class=\"d-grid gap-2 d-md-flex justify-content-md-end\" style=\"width: 90%;\">\r\n");
      out.write("\t                <button type=\"button\" class=\"btn btn-primary\">등록하기</button>\r\n");
      out.write("\t                <button type=\"button\" class=\"btn btn-secondary\">취소</button>\r\n");
      out.write("\t                </div>\r\n");
      out.write("                </td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<br />\r\n");
      out.write("\t<br />\r\n");
      out.write("\t<br />\r\n");
      out.write("\t<br />\r\n");
      out.write("\t<br />\r\n");
      out.write("\t<br />\r\n");
      out.write("\t<br />\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fimport_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:import
    org.apache.taglibs.standard.tag.rt.core.ImportTag _jspx_th_c_005fimport_005f0 = (org.apache.taglibs.standard.tag.rt.core.ImportTag) _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.ImportTag.class);
    boolean _jspx_th_c_005fimport_005f0_reused = false;
    try {
      _jspx_th_c_005fimport_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fimport_005f0.setParent(null);
      // /user_delievery_modify.jsp(44,1) name = url type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fimport_005f0.setUrl("admin/comfit_header_user.jsp");
      int[] _jspx_push_body_count_c_005fimport_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fimport_005f0 = _jspx_th_c_005fimport_005f0.doStartTag();
        if (_jspx_th_c_005fimport_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fimport_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fimport_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fimport_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.reuse(_jspx_th_c_005fimport_005f0);
      _jspx_th_c_005fimport_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fimport_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fimport_005f0_reused);
    }
    return false;
  }
}
